import type { Metadata } from "next";

import { MarketingPageShell } from "@/components/MarketingPageShell";

export const metadata: Metadata = {
  title: "Terms of Service | TransitIQ Lite",
  description: "Terms of service for TransitIQ Lite.",
};

function TermsSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-lg shadow-slate-200/50">
      <h2 className="text-xl font-bold tracking-tight text-slate-950">
        {title}
      </h2>
      <div className="mt-4 space-y-4 text-sm leading-7 text-slate-600">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <MarketingPageShell
      title="Terms of Service"
      subtitle="Effective Date: April 17, 2026"
    >
      <div className="space-y-6">
        <TermsSection title="Introduction">
          <p>By using TransitIQ Lite, you agree to these terms.</p>
        </TermsSection>

        <TermsSection title="Description of Service">
          <p>
            TransitIQ Lite is a free AI-powered tool that helps university
            students understand campus transit information. It uses AI to
            analyze uploaded transit documents and answer questions.
          </p>
        </TermsSection>

        <TermsSection title="Acceptable Use">
          <p>
            You may use the service for personal, non-commercial use. You must
            not:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li>Upload harmful, illegal, or inappropriate content.</li>
            <li>Attempt to reverse-engineer or exploit the service.</li>
            <li>Use automated bots to access the service.</li>
            <li>
              Misrepresent AI-generated answers as official university
              information.
            </li>
          </ul>
        </TermsSection>

        <TermsSection title="AI Disclaimer">
          <p>
            Answers are generated by artificial intelligence, specifically
            OpenAI GPT-4o. While we strive for accuracy, AI-generated answers
            may contain errors.
          </p>
          <p>
            TransitIQ Lite is not an official source of transit information.
            Always verify schedules with your university&apos;s official transit
            website. We are not responsible for missed shuttles, incorrect
            schedules, or any decisions made based on AI-generated answers.
          </p>
        </TermsSection>

        <TermsSection title="Intellectual Property">
          <p>
            TransitIQ Lite is owned by Krushal Kalkani. The design, code, and
            branding are protected. University transit data is sourced from
            publicly available information.
          </p>
        </TermsSection>

        <TermsSection title="Limitation of Liability">
          <p>
            TransitIQ Lite is provided &quot;as is&quot; without warranties. We
            are not liable for any damages arising from your use of the service.
          </p>
        </TermsSection>

        <TermsSection title="Termination">
          <p>We may discontinue the service at any time without notice.</p>
        </TermsSection>

        <TermsSection title="Changes">
          <p>
            We may update these terms. Continued use constitutes acceptance.
          </p>
        </TermsSection>

        <TermsSection title="Contact">
          <p>
            Questions about these terms can be sent to{" "}
            <a
              href="mailto:krushal.kalkani@icloud.com"
              className="font-semibold text-fau-blue hover:underline"
            >
              krushal.kalkani@icloud.com
            </a>
            .
          </p>
        </TermsSection>
      </div>
    </MarketingPageShell>
  );
}
